In [20]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as QDA




#PCA dimension reduced files
X_train = np.load("../X_train_pca.npk")
X_test = np.load("../X_test_pca.npk")

#keeps the totalRansactionRevenue, class_pred = 0 if didnt buy anythin and 1 if did
y_test = pd.read_pickle("../y_test.pkl")
y_train = pd.read_pickle("../y_train.pkl")

# LDA

In [10]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'shrinkage': [None, 'auto'],
    'solver': ['eigen', 'lsqr']
}

clf = LDA()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = clf, param_grid = param_grid, scoring = 'f1',
                          cv = 3, verbose = 10,return_train_score=True)

In [11]:
grid_search.fit(X_train, y_train['class_pred'])


Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] shrinkage=None, solver=eigen ....................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV]  shrinkage=None, solver=eigen, score=0.368243243243, total=   1.8s
[CV] shrinkage=None, solver=eigen ....................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.0s remaining:    0.0s


[CV]  shrinkage=None, solver=eigen, score=0.357248773811, total=   1.6s
[CV] shrinkage=None, solver=eigen ....................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    3.8s remaining:    0.0s


[CV]  shrinkage=None, solver=eigen, score=0.35349252399, total=   1.6s
[CV] shrinkage=None, solver=lsqr .....................................


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    5.6s remaining:    0.0s


[CV]  shrinkage=None, solver=lsqr, score=0.367093421219, total=   1.6s
[CV] shrinkage=None, solver=lsqr .....................................


[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    7.4s remaining:    0.0s


[CV]  shrinkage=None, solver=lsqr, score=0.358182052272, total=   1.8s
[CV] shrinkage=None, solver=lsqr .....................................


[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    9.4s remaining:    0.0s


[CV]  shrinkage=None, solver=lsqr, score=0.354746164401, total=   1.7s
[CV] shrinkage=auto, solver=eigen ....................................


[Parallel(n_jobs=1)]: Done   6 out of   6 | elapsed:   11.3s remaining:    0.0s


[CV]  shrinkage=auto, solver=eigen, score=0.367893729596, total=   2.7s
[CV] shrinkage=auto, solver=eigen ....................................


[Parallel(n_jobs=1)]: Done   7 out of   7 | elapsed:   14.2s remaining:    0.0s


[CV]  shrinkage=auto, solver=eigen, score=0.356313993174, total=   2.9s
[CV] shrinkage=auto, solver=eigen ....................................


[Parallel(n_jobs=1)]: Done   8 out of   8 | elapsed:   17.3s remaining:    0.0s


[CV]  shrinkage=auto, solver=eigen, score=0.35284951024, total=   3.1s
[CV] shrinkage=auto, solver=lsqr .....................................


[Parallel(n_jobs=1)]: Done   9 out of   9 | elapsed:   20.6s remaining:    0.0s


[CV]  shrinkage=auto, solver=lsqr, score=0.366615853659, total=   2.1s
[CV] shrinkage=auto, solver=lsqr .....................................
[CV]  shrinkage=auto, solver=lsqr, score=0.358432181537, total=   2.4s
[CV] shrinkage=auto, solver=lsqr .....................................
[CV]  shrinkage=auto, solver=lsqr, score=0.354367112333, total=   2.0s


[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:   27.7s finished


GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'shrinkage': [None, 'auto'], 'solver': ['eigen', 'lsqr']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score=True,
       scoring='f1', verbose=10)

In [13]:
grid_search.best_params_

{'shrinkage': None, 'solver': 'lsqr'}

In [16]:
grid_search.best_estimator_.fit(X_train, y_train['class_pred'])
pred = grid_search.best_estimator_.predict(X_test)
confusion_matrix(y_test['class_pred'], pred)


array([[368345,   5508],
       [  1883,   1978]])

In [22]:
print(cross_val_score(grid_search.best_estimator_, X_train, y_train['class_pred'], cv=5, scoring = 'f1'))



[0.36098374 0.37614885 0.34768348 0.35824688 0.35529608]


# QDA

In [26]:
qda = QDA()

# print(cross_val_score(qda, X_train, y_train['class_pred'], cv=5, scoring = 'f1'))

qda.fit(X_train, y_train['class_pred'])
qdapred = qda.predict(X_test)
confusion_matrix(y_test['class_pred'], qdapred)


array([[279691,  94162],
       [   246,   3615]])